"""Generate the frontend's copy of the backend contract.

The dashboard must never restate anything the backend already knows. Three
artefacts are derived here rather than hand-written in TypeScript:

* ``openapi.json``            - the API schema, from the live FastAPI app.
* ``reason-codes.generated.ts`` - the reason-code registry, including the
  plain-language operator sentence for every code (standing rule 9: a score never
  renders without a reason code, and that code has to say something a human reads).
* ``tokens.generated.ts``     - the numeric design tokens the UI branches on,
  parsed out of ``design/tokens/tokens.css``. The trust thresholds live in the
  token file because the marker colours and the classification have to agree; a
  second copy in TypeScript is how they silently stop agreeing.

Everything written here is checked in, so the frontend builds and tests without a
Python environment. ``--check`` re-derives into memory and diffs against what is
committed: that is the CI drift gate. If the backend schema, the registry, or the
tokens change and the generated files are stale, the build fails rather than the
dashboard quietly describing a system that no longer exists.

Determinism matters (standing rule 8): output is sorted and the writer is
byte-stable, so re-running on an unchanged input produces an identical file.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[1]
OUT_DIR = REPO / "apps" / "web" / "src" / "api"
TOKENS = REPO / "design" / "tokens" / "tokens.css"

BANNER = "// Generated by scripts/gen_frontend_contract.py. Do not edit by hand."


# --------------------------------------------------------------------- openapi
def build_openapi() -> str:
    """Serialise the live FastAPI schema.

    ``create_app()`` builds an engine but never connects, so this runs with no
    database and no data present.
    """
    from provenance.api.app import create_app

    schema = create_app().openapi()
    return json.dumps(schema, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


# ---------------------------------------------------------------- reason codes
def build_reason_codes() -> str:
    """Emit the registry as a typed, frozen TypeScript record."""
    from provenance.config.reason_codes import REASON_CODES, Category, Severity

    categories = " | ".join(f'"{c.value}"' for c in Category)
    severities = " | ".join(f'"{s.value}"' for s in Severity)

    lines = [
        BANNER,
        "//",
        "// The reason-code registry, mirrored from src/provenance/config/reason_codes.py.",
        "// `sentence` is the operator-facing template; placeholders are filled from a",
        "// detector's evidence dict by renderReasonSentence() in ./reason-codes.ts.",
        "",
        f"export type ReasonCodeCategory = {categories};",
        "",
        f"export type ReasonCodeSeverity = {severities};",
        "",
        "export interface ReasonCodeDef {",
        "  readonly code: string;",
        "  readonly name: string;",
        "  readonly sentence: string;",
        "  readonly category: ReasonCodeCategory;",
        "  readonly severity: ReasonCodeSeverity;",
        "  /** False for coverage and trust codes: these never touch the defect rate. */",
        "  readonly countsTowardDefectRate: boolean;",
        "  readonly implementedInPhase: number;",
        "}",
        "",
        "export const REASON_CODES: Readonly<Record<string, ReasonCodeDef>> = {",
    ]
    for code in sorted(REASON_CODES):
        rc = REASON_CODES[code]
        lines += [
            f"  {code}: {{",
            f"    code: {_ts(rc.code)},",
            f"    name: {_ts(rc.name)},",
            f"    sentence: {_ts(rc.sentence)},",
            f"    category: {_ts(rc.category.value)},",
            f"    severity: {_ts(rc.severity.value)},",
            f"    countsTowardDefectRate: {str(rc.counts_toward_defect_rate).lower()},",
            f"    implementedInPhase: {rc.implemented_in_phase},",
            "  },",
        ]
    lines += ["};", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------- tokens
_NUMERIC_TOKENS = ("--prov-threshold-verified", "--prov-threshold-fault")
_SHAPE_TOKENS = (
    "--prov-shape-verified",
    "--prov-shape-degraded",
    "--prov-shape-fault",
    "--prov-shape-ambiguous",
    "--prov-shape-no-coverage",
)


def _token_value(css: str, name: str) -> str:
    match = re.search(rf"^\s*{re.escape(name)}\s*:\s*([^;]+);", css, re.MULTILINE)
    if match is None:
        raise SystemExit(
            f"Token {name!r} is missing from {TOKENS.relative_to(REPO)}. The UI branches "
            "on it, so the generator fails loudly rather than inventing a default."
        )
    return match.group(1).strip().strip('"')


def build_tokens() -> str:
    """Emit the numeric and shape tokens the UI has to branch on in TypeScript.

    Colour never appears here: colour stays in CSS, referenced through var(). Only
    the values a component makes a *decision* with are lifted into TS.
    """
    css = TOKENS.read_text(encoding="utf-8")
    verified = float(_token_value(css, "--prov-threshold-verified"))
    fault = float(_token_value(css, "--prov-threshold-fault"))
    shapes = {name: _token_value(css, name) for name in _SHAPE_TOKENS}

    lines = [
        BANNER,
        "//",
        "// Parsed from design/tokens/tokens.css. Only values the UI *branches* on live",
        "// here - never colour, which stays in CSS behind var(). The trust thresholds",
        "// are in the token file so the marker colour and the classification cannot",
        "// disagree; this file keeps TypeScript reading the same single source.",
        "",
        "/** Trust at or above this is verified. */",
        f"export const TRUST_VERIFIED_AT = {verified};",
        "",
        "/** Trust below this is a fault. Between the two is anomaly/ambiguity. */",
        f"export const TRUST_FAULT_BELOW = {fault};",
        "",
        "/** Shape channel, so colour is never the only signal a state carries. */",
        "export const STATE_SHAPES = {",
    ]
    for name in _SHAPE_TOKENS:
        key = name.removeprefix("--prov-shape-")
        camel = key.split("-")[0] + "".join(p.title() for p in key.split("-")[1:])
        lines.append(f"  {camel}: {_ts(shapes[name])},")
    lines += ["} as const;", ""]
    return "\n".join(lines)


def _ts(value: Any) -> str:
    """JSON-encode a Python value into a TypeScript literal."""
    return json.dumps(value, ensure_ascii=False)


# ----------------------------------------------------------------------- entry
ARTEFACTS = {
    "openapi.json": build_openapi,
    "reason-codes.generated.ts": build_reason_codes,
    "tokens.generated.ts": build_tokens,
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; exit non-zero if any committed artefact is stale.",
    )
    args = parser.parse_args(argv)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    stale: list[str] = []
    for name, build in ARTEFACTS.items():
        want = build()
        path = OUT_DIR / name
        if args.check:
            have = path.read_text(encoding="utf-8") if path.exists() else ""
            if have != want:
                stale.append(name)
        else:
            path.write_text(want, encoding="utf-8")

    if args.check:
        if stale:
            print(
                "Frontend contract is stale: "
                + ", ".join(stale)
                + "\nThe backend schema, the reason-code registry, or the design tokens "
                "changed without the generated client being rebuilt.\n"
                "Run: make web-contract",
                file=sys.stderr,
            )
            return 1
        print("Frontend contract is current.")
        return 0

    print(f"Wrote {len(ARTEFACTS)} artefacts to {OUT_DIR.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
