"""Derive the reversed horizontal lockup from the approved one.

The lockup's wordmark is inked in the brand's near-black (``#031436``), which is
correct on light surfaces and invisible on the dark theme — which is the default
theme for this map-first operations UI. A reversed lockup is ordinary brand-system
work, not a palette change: the geometry, the mark, and its gradient are untouched,
and the only substitution is the wordmark's ink for ``--prov-white``, which is
already in the palette.

Generating it rather than hand-drawing it means the two lockups cannot drift.
``tests/architecture/test_brand.py`` asserts exactly that.

    python scripts/gen_reversed_lockup.py [--check]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SOURCE = REPO / "design" / "logo" / "provenance-lockup-horizontal.svg"
TARGET = REPO / "design" / "logo" / "provenance-lockup-horizontal-reversed.svg"
MIRROR = REPO / "apps" / "web" / "public" / "provenance-lockup-horizontal-reversed.svg"

WORDMARK_INK = 'fill="#031436"'
REVERSED_INK = 'fill="#FFFFFF"'

_NOTE = (
    "<title>Provenance (reversed)</title>\n"
    "  <!-- Reversed lockup: geometry identical to provenance-lockup-horizontal.svg,\n"
    "       with the wordmark inked in the prov-white token so it stays legible on the dark\n"
    "       theme's surfaces. The mark's gradient is unchanged. Generated by\n"
    "       scripts/gen_reversed_lockup.py; do not hand-edit. -->"
)


def build() -> str:
    text = SOURCE.read_text(encoding="utf-8")
    if text.count(WORDMARK_INK) != 1:
        raise SystemExit(
            f"Expected exactly one wordmark fill {WORDMARK_INK} in {SOURCE.name}; the lockup "
            "changed shape, so this script needs revisiting rather than silently guessing."
        )
    return text.replace(WORDMARK_INK, REVERSED_INK).replace("<title>Provenance</title>", _NOTE)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Exit non-zero if stale.")
    args = parser.parse_args(argv)

    want = build()
    if args.check:
        stale = [p for p in (TARGET, MIRROR) if not p.exists() or p.read_text("utf-8") != want]
        if stale:
            print(
                "Reversed lockup is stale: " + ", ".join(str(p) for p in stale),
                file=sys.stderr,
            )
            return 1
        print("Reversed lockup is current.")
        return 0

    for path in (TARGET, MIRROR):
        path.write_text(want, encoding="utf-8")
    print(f"Wrote {TARGET.relative_to(REPO)} and {MIRROR.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
