/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audit/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_v1_audit_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audit/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_v1_audit_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/defects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Defects */
        get: operations["list_defects_v1_defects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deweather/{station_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deweather */
        get: operations["get_deweather_v1_deweather__station_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/explain/{defect_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Explain */
        get: operations["get_explain_v1_explain__defect_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/export/audit-trail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit Trail */
        get: operations["audit_trail_v1_export_audit_trail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/quality/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quality Summary */
        get: operations["quality_summary_v1_quality_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/readings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Readings */
        get: operations["list_readings_v1_readings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stations */
        get: operations["list_stations_v1_stations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stations/{station_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Station */
        get: operations["get_station_v1_stations__station_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trust/{station_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trust */
        get: operations["get_trust_v1_trust__station_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AttributionOut */
        AttributionOut: {
            /** Feature */
            feature: string;
            /** Feature Value */
            feature_value: number;
            /** Provenance */
            provenance: string;
            /** Value */
            value: number;
        };
        /** AuditRunOut */
        AuditRunOut: {
            /** Code Version */
            code_version: string;
            /** Config Hash */
            config_hash: string;
            /** Conventional Completeness Pct */
            conventional_completeness_pct: number;
            /** Data Checksum */
            data_checksum: string;
            /** Defect Rate */
            defect_rate: number;
            /** Generated At */
            generated_at: string;
            /** Id */
            id: string;
            /** Ingest Batch Id */
            ingest_batch_id?: string | null;
            /** N Covered Cells */
            n_covered_cells: number;
            /** N Defective Cells */
            n_defective_cells: number;
            /** N Rows */
            n_rows: number;
        };
        /** ComponentOut */
        ComponentOut: {
            /** Contribution */
            contribution: number;
            /** Detail */
            detail: string;
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            };
            /** Is Placeholder */
            is_placeholder: boolean;
            /** Name */
            name: string;
            /** Value */
            value: number;
            /** Weight */
            weight: number;
        };
        /** DefectOut */
        DefectOut: {
            /** Audit Run Id */
            audit_run_id: string;
            /** Counts Toward Rate */
            counts_toward_rate: boolean;
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            };
            /** Id */
            id: number;
            /** Parameter */
            parameter: string;
            /** Reason Code */
            reason_code: string;
            /** Severity */
            severity: string;
            /** Station Id */
            station_id: string;
            /** Timestamp Utc */
            timestamp_utc: string;
        };
        /** DeweatherPointOut */
        DeweatherPointOut: {
            /** Actual */
            actual: number;
            /** Predicted */
            predicted: number;
            /** Residual */
            residual: number;
            /** Timestamp Utc */
            timestamp_utc: string;
        };
        /**
         * DeweatherSeriesOut
         * @description A station's deweathered series for one pollutant: raw vs weather-predicted vs residual.
         *
         *     The before/after view (§7.6): ``actual`` is what the sensor reported, ``predicted`` is
         *     what weather and time alone explain, and ``residual`` is what is left — the part
         *     anomaly detection should see. ``degraded`` is true when no residuals have been stored
         *     (no model trained), in which case ``series`` is empty and the client says so.
         */
        DeweatherSeriesOut: {
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /** Model Version */
            model_version?: string | null;
            /** Parameter */
            parameter: string;
            /** Series */
            series?: components["schemas"]["DeweatherPointOut"][];
            /** Station Id */
            station_id: string;
        };
        /** EventOut */
        EventOut: {
            /** Audit Run Id */
            audit_run_id: string;
            /** Category */
            category: string;
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            };
            /** Headline */
            headline: string;
            /** Id */
            id: number;
            /** Parameter */
            parameter: string;
            /** Rank */
            rank: number;
            /** Reason Code */
            reason_code: string;
            /** Severity */
            severity: string;
            /** Station Id */
            station_id: string;
            /** Timestamp Utc */
            timestamp_utc: string;
            /** Verdict */
            verdict?: string | null;
        };
        /**
         * ExplainOut
         * @description A per-defect explanation. Never a bare score: it always carries a sentence.
         *
         *     ``method`` records how the explanation was produced — ``model`` (SHAP over a tree
         *     model), ``rule`` (a deterministic detector decided it), or ``degraded`` (no model
         *     artefact was available, so the statistics-layer reason is returned instead). When
         *     ``degraded`` is true the ``attributions`` list is empty by construction and the
         *     response says so, per standing rule 6.
         */
        ExplainOut: {
            /** Attributions */
            attributions?: components["schemas"]["AttributionOut"][];
            /** Base Value */
            base_value?: number | null;
            /** Defect Id */
            defect_id: number;
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /** Fault Class */
            fault_class?: string | null;
            /** Method */
            method: string;
            /** Model Versions */
            model_versions?: {
                [key: string]: string;
            };
            /** Notes */
            notes?: string[];
            /** Parameter */
            parameter: string;
            /** Predicted Class */
            predicted_class?: string | null;
            /** Prediction */
            prediction?: number | null;
            /** Reason Code */
            reason_code: string;
            /** Reconstructs */
            reconstructs?: boolean | null;
            /** Residual */
            residual?: number | null;
            /** Sentence */
            sentence: string;
            /** Station Id */
            station_id: string;
            /** Timestamp Utc */
            timestamp_utc: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
        };
        /** Page[AuditRunOut] */
        Page_AuditRunOut_: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["AuditRunOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[DefectOut] */
        Page_DefectOut_: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["DefectOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[EventOut] */
        Page_EventOut_: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["EventOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[ReadingOut] */
        Page_ReadingOut_: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["ReadingOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[StationOut] */
        Page_StationOut_: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["StationOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[TrustScoreOut] */
        Page_TrustScoreOut_: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["TrustScoreOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** QualityStationOut */
        QualityStationOut: {
            /** Components */
            components?: components["schemas"]["ComponentOut"][];
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            };
            /** Flag Count */
            flag_count: number;
            /** Health */
            health: number | null;
            /** Last Reading At */
            last_reading_at: string | null;
            /** N Parameters */
            n_parameters: number;
            /** Reason Codes */
            reason_codes?: string[];
            /** Station Id */
            station_id: string;
            /** Trust */
            trust: number | null;
            /** Zone Type */
            zone_type: string | null;
        };
        /** QualitySummaryOut */
        QualitySummaryOut: {
            /** Audit Run Id */
            audit_run_id: string;
            /** Stations */
            stations: components["schemas"]["QualityStationOut"][];
        };
        /** ReadingOut */
        ReadingOut: {
            /** Instrument Id */
            instrument_id?: string | null;
            /** Parameter */
            parameter: string;
            /** Reason Codes */
            reason_codes?: string[] | null;
            /** Row Hash */
            row_hash: string;
            /** Source File */
            source_file: string;
            /** Station Id */
            station_id: string;
            /** Timestamp Utc */
            timestamp_utc: string;
            /** Unit */
            unit: string;
            /** Value */
            value: number | null;
        };
        /** ReadyOut */
        ReadyOut: {
            /** Database */
            database: string;
            /** Status */
            status: string;
        };
        /** RiskOut */
        RiskOut: {
            /** Population Exposure */
            population_exposure: number;
            /** Population Exposure Stubbed */
            population_exposure_stubbed: boolean;
            /** Severity Vs Threshold */
            severity_vs_threshold: number;
            /** Trust */
            trust: number;
            /** Value */
            value: number;
        };
        /** StationOut */
        StationOut: {
            /** Coverage */
            coverage?: {
                [key: string]: number;
            };
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Name */
            name?: string | null;
            /** Station Id */
            station_id: string;
            /** Zone Type */
            zone_type?: string | null;
        };
        /**
         * TrustScoreOut
         * @description A trust score, inseparable from its explanation.
         *
         *     ``components`` and ``reason_codes`` are required and validated non-empty: a
         *     ``TrustScoreOut`` cannot be constructed as a bare number.
         */
        TrustScoreOut: {
            /** Components */
            components: components["schemas"]["ComponentOut"][];
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            };
            /** Notes */
            notes?: string[];
            /** Reason Codes */
            reason_codes: string[];
            risk: components["schemas"]["RiskOut"];
            /** Station Id */
            station_id: string;
            /** Timestamp Utc */
            timestamp_utc: string;
            /** Trust */
            trust: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VersionOut */
        VersionOut: {
            /** Config Hash */
            config_hash: string;
            /** Git Sha */
            git_sha: string;
            /** Model Versions */
            model_versions: {
                [key: string]: string;
            };
            /** Trust Config Hash */
            trust_config_hash: string;
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyOut"];
                };
            };
        };
    };
    list_runs_v1_audit_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AuditRunOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_v1_audit_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_defects_v1_defects_get: {
        parameters: {
            query?: {
                code?: string | null;
                station?: string | null;
                severity?: string | null;
                start?: string | null;
                end?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DefectOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deweather_v1_deweather__station_id__get: {
        parameters: {
            query: {
                /** @description The pollutant to show the deweathered series for. */
                parameter: string;
            };
            header?: never;
            path: {
                station_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeweatherSeriesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_v1_events_get: {
        parameters: {
            query?: {
                station?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_EventOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_explain_v1_explain__defect_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                defect_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_trail_v1_export_audit_trail_get: {
        parameters: {
            query?: {
                /** @description Audit run; defaults to the latest. */
                run_id?: string | null;
                format?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quality_summary_v1_quality_summary_get: {
        parameters: {
            query?: {
                /** @description Audit run; defaults to the latest. */
                run_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualitySummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_readings_v1_readings_get: {
        parameters: {
            query?: {
                station?: string | null;
                parameter?: string | null;
                start?: string | null;
                end?: string | null;
                /** @description Annotate with audit reason codes. */
                quality_flagged?: boolean;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ReadingOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stations_v1_stations_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_StationOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_station_v1_stations__station_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                station_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trust_v1_trust__station_id__get: {
        parameters: {
            query?: {
                /** @description Return the score history instead of the latest. */
                series?: boolean;
                start?: string | null;
                end?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                station_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrustScoreOut"] | components["schemas"]["Page_TrustScoreOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionOut"];
                };
            };
        };
    };
}
