/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/model-drift": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Model Drift
         * @description The model-drift monitor (§11): defect-rate drift by station, R², coverage, confusion.
         *
         *     Deliberately a *different plane* from ``/metrics`` (infra health) — model health and
         *     service health are separate questions with separate dashboards.
         */
        get: operations["model_drift_v1_admin_model_drift_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/retrain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retrain */
        post: operations["retrain_v1_admin_retrain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Status */
        get: operations["admin_status_v1_admin_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alerts */
        get: operations["list_alerts_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audit/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_v1_audit_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audit/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_v1_audit_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/decision/dispatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dispatch Alert */
        post: operations["dispatch_alert_v1_decision_dispatch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/decision/signoff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Signoff */
        post: operations["create_signoff_v1_decision_signoff_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/defects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Defects */
        get: operations["list_defects_v1_defects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deweather/{station_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deweather */
        get: operations["get_deweather_v1_deweather__station_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/explain/{defect_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Explain */
        get: operations["get_explain_v1_explain__defect_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/export/audit-trail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit Trail */
        get: operations["audit_trail_v1_export_audit_trail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/graph/attention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Attention Overlay */
        get: operations["get_attention_overlay_v1_graph_attention_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/maintenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Maintenance */
        get: operations["list_maintenance_v1_maintenance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/maintenance/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rebuild */
        post: operations["rebuild_v1_maintenance_rebuild_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/maintenance/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Item */
        get: operations["get_item_v1_maintenance__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/maintenance/{item_id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transition */
        post: operations["transition_v1_maintenance__item_id__transition_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/quality/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quality Summary */
        get: operations["quality_summary_v1_quality_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/readings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Readings */
        get: operations["list_readings_v1_readings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reference/bus-stops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bus Stops */
        get: operations["bus_stops_v1_reference_bus_stops_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reference/traffic-counters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Traffic Counters */
        get: operations["traffic_counters_v1_reference_traffic_counters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stations */
        get: operations["list_stations_v1_stations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stations/{station_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Station */
        get: operations["get_station_v1_stations__station_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trust/{station_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trust */
        get: operations["get_trust_v1_trust__station_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AttentionEdgeOut */
        AttentionEdgeOut: {
            /** Attention */
            attention: number;
            /** Dst */
            dst: string;
            /** Edge Weight */
            edge_weight: number;
            /** Src */
            src: string;
        };
        /**
         * AttentionOverlayOut
         * @description The HST-GAT's attention over the graph edges, for the map overlay (§8).
         *
         *     ``available=False`` means no trained HST-GAT artefact exists, or its target
         *     parameter is not present in the currently loaded data — a fact about the model,
         *     not an empty overlay (standing rule 6): the map disables the toggle with
         *     ``reason`` as its tooltip rather than rendering nothing silently or erroring.
         *     A read-out of what the model attended to, never an accuracy claim (standing
         *     rule 4) — there is no score here, only edges and their weights.
         */
        AttentionOverlayOut: {
            /** At */
            at?: string | null;
            /** Available */
            available: boolean;
            /** Reason */
            reason?: string | null;
            /** Relations */
            relations?: {
                [key: string]: components["schemas"]["AttentionEdgeOut"][];
            };
            /** Target Parameter */
            target_parameter?: string | null;
        };
        /** AttributionOut */
        AttributionOut: {
            /** Feature */
            feature: string;
            /** Feature Value */
            feature_value: number;
            /** Provenance */
            provenance: string;
            /** Value */
            value: number;
        };
        /** AuditRunOut */
        AuditRunOut: {
            /** Code Version */
            code_version: string;
            /** Config Hash */
            config_hash: string;
            /** Conventional Completeness Pct */
            conventional_completeness_pct: number;
            /** Data Checksum */
            data_checksum: string;
            /** Defect Rate */
            defect_rate: number;
            /** Generated At */
            generated_at: string;
            /** Id */
            id: string;
            /** Ingest Batch Id */
            ingest_batch_id?: string | null;
            /** N Covered Cells */
            n_covered_cells: number;
            /** N Defective Cells */
            n_defective_cells: number;
            /** N Rows */
            n_rows: number;
        };
        /** BusStopOut */
        BusStopOut: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** N Routes */
            n_routes: number;
            /** Stop Id */
            stop_id: string;
        };
        /** ComponentOut */
        ComponentOut: {
            /** Contribution */
            contribution: number;
            /** Detail */
            detail: string;
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            };
            /** Is Placeholder */
            is_placeholder: boolean;
            /** Name */
            name: string;
            /** Value */
            value: number;
            /** Weight */
            weight: number;
        };
        /** DefectOut */
        DefectOut: {
            /** Audit Run Id */
            audit_run_id: string;
            /** Counts Toward Rate */
            counts_toward_rate: boolean;
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            };
            /** Id */
            id: number;
            /** Parameter */
            parameter: string;
            /** Reason Code */
            reason_code: string;
            /** Severity */
            severity: string;
            /** Station Id */
            station_id: string;
            /** Timestamp Utc */
            timestamp_utc: string;
        };
        /** DeweatherPointOut */
        DeweatherPointOut: {
            /** Actual */
            actual: number;
            /** Predicted */
            predicted: number;
            /** Residual */
            residual: number;
            /** Timestamp Utc */
            timestamp_utc: string;
        };
        /**
         * DeweatherSeriesOut
         * @description A station's deweathered series for one pollutant: raw vs weather-predicted vs residual.
         *
         *     The before/after view (§7.6): ``actual`` is what the sensor reported, ``predicted`` is
         *     what weather and time alone explain, and ``residual`` is what is left — the part
         *     anomaly detection should see. ``degraded`` is true when no residuals have been stored
         *     (no model trained), in which case ``series`` is empty and the client says so.
         */
        DeweatherSeriesOut: {
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /** Model Version */
            model_version?: string | null;
            /** Parameter */
            parameter: string;
            /** Series */
            series?: components["schemas"]["DeweatherPointOut"][];
            /** Station Id */
            station_id: string;
        };
        /** DispatchIn */
        DispatchIn: {
            /** Channel */
            channel: string;
            /** Event Id */
            event_id: number;
            /** Signoff Id */
            signoff_id: string;
        };
        /** EventOut */
        EventOut: {
            /** Audit Run Id */
            audit_run_id: string;
            /** Category */
            category: string;
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            };
            /** Headline */
            headline: string;
            /** Id */
            id: number;
            /** Parameter */
            parameter: string;
            /** Rank */
            rank: number;
            /** Reason Code */
            reason_code: string;
            /** Severity */
            severity: string;
            /** Station Id */
            station_id: string;
            /** Timestamp Utc */
            timestamp_utc: string;
            /** Verdict */
            verdict?: string | null;
        };
        /**
         * ExplainOut
         * @description A per-defect explanation. Never a bare score: it always carries a sentence.
         *
         *     ``method`` records how the explanation was produced — ``model`` (SHAP over a tree
         *     model), ``rule`` (a deterministic detector decided it), or ``degraded`` (no model
         *     artefact was available, so the statistics-layer reason is returned instead). When
         *     ``degraded`` is true the ``attributions`` list is empty by construction and the
         *     response says so, per standing rule 6.
         */
        ExplainOut: {
            /** Attributions */
            attributions?: components["schemas"]["AttributionOut"][];
            /** Base Value */
            base_value?: number | null;
            /** Defect Id */
            defect_id: number;
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /** Fault Class */
            fault_class?: string | null;
            /** Method */
            method: string;
            /** Model Versions */
            model_versions?: {
                [key: string]: string;
            };
            /** Notes */
            notes?: string[];
            /** Parameter */
            parameter: string;
            /** Predicted Class */
            predicted_class?: string | null;
            /** Prediction */
            prediction?: number | null;
            /** Reason Code */
            reason_code: string;
            /** Reconstructs */
            reconstructs?: boolean | null;
            /** Residual */
            residual?: number | null;
            /** Sentence */
            sentence: string;
            /** Station Id */
            station_id: string;
            /** Timestamp Utc */
            timestamp_utc: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
        };
        /** Page[AuditRunOut] */
        Page_AuditRunOut_: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["AuditRunOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[DefectOut] */
        Page_DefectOut_: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["DefectOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[EventOut] */
        Page_EventOut_: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["EventOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[ReadingOut] */
        Page_ReadingOut_: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["ReadingOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[StationOut] */
        Page_StationOut_: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["StationOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[TrustScoreOut] */
        Page_TrustScoreOut_: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["TrustScoreOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[dict[str, Any]] */
        Page_dict_str__Any__: {
            /** Count */
            count: number;
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** QualityStationOut */
        QualityStationOut: {
            /**
             * Absent Cells
             * @default 0
             */
            absent_cells: number;
            /** Components */
            components?: components["schemas"]["ComponentOut"][];
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            };
            /** Expected Cells */
            expected_cells?: number | null;
            /** Flag Count */
            flag_count: number;
            /** Health */
            health: number | null;
            /** Last Calibration At */
            last_calibration_at?: string | null;
            /** Last Reading At */
            last_reading_at: string | null;
            /** N Parameters */
            n_parameters: number;
            /** Reason Codes */
            reason_codes?: string[];
            /** Station Id */
            station_id: string;
            /** Trust */
            trust: number | null;
            /** Uptime Pct */
            uptime_pct?: number | null;
            /** Zone Type */
            zone_type: string | null;
        };
        /** QualitySummaryOut */
        QualitySummaryOut: {
            /** Audit Run Id */
            audit_run_id: string;
            /** Stations */
            stations: components["schemas"]["QualityStationOut"][];
        };
        /** ReadingOut */
        ReadingOut: {
            /** Instrument Id */
            instrument_id?: string | null;
            /** Parameter */
            parameter: string;
            /** Reason Codes */
            reason_codes?: string[] | null;
            /** Row Hash */
            row_hash: string;
            /** Source File */
            source_file: string;
            /** Station Id */
            station_id: string;
            /** Timestamp Utc */
            timestamp_utc: string;
            /** Unit */
            unit: string;
            /** Value */
            value: number | null;
        };
        /** ReadyOut */
        ReadyOut: {
            /** Database */
            database: string;
            /** Status */
            status: string;
        };
        /** RebuildIn */
        RebuildIn: {
            /**
             * Run Id
             * @description Audit run; defaults to the latest.
             */
            run_id?: string | null;
        };
        /**
         * ReferenceCountersOut
         * @description ``available=False`` means no Enclod archive CSVs were found under the data
         *     root — distinct from the counters existing but carrying no coordinate.
         */
        ReferenceCountersOut: {
            /** Available */
            available: boolean;
            /** Counters */
            counters: components["schemas"]["TrafficCounterOut"][];
        };
        /**
         * ReferenceStopsOut
         * @description ``available=False`` means no GTFS bundle was found — a coverage fact, not an
         *     empty layer (standing rule 3): the map must tell the two apart.
         */
        ReferenceStopsOut: {
            /** Available */
            available: boolean;
            /** Stops */
            stops: components["schemas"]["BusStopOut"][];
        };
        /** RetrainIn */
        RetrainIn: {
            /** Reason */
            reason?: string | null;
            /**
             * Target
             * @description One of ['deweather', 'fault', 'hstgat'].
             */
            target: string;
        };
        /** RiskOut */
        RiskOut: {
            /** Population Exposure */
            population_exposure: number;
            /** Population Exposure Stubbed */
            population_exposure_stubbed: boolean;
            /** Severity Vs Threshold */
            severity_vs_threshold: number;
            /** Trust */
            trust: number;
            /** Value */
            value: number;
        };
        /** SignoffIn */
        SignoffIn: {
            /**
             * Channel
             * @description webhook | email | sms.
             */
            channel: string;
            /** Event Id */
            event_id: number;
            /**
             * Evidence
             * @description What the operator saw; defaults to the event's evidence.
             */
            evidence?: {
                [key: string]: unknown;
            } | null;
            /** Model Version */
            model_version?: string | null;
            /**
             * Operator
             * @description Who is signing off.
             * @default operator
             */
            operator: string;
            /**
             * Ttl Seconds
             * @default 900
             */
            ttl_seconds: number;
        };
        /** StationOut */
        StationOut: {
            /** Coverage */
            coverage?: {
                [key: string]: number;
            };
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Name */
            name?: string | null;
            /** Station Id */
            station_id: string;
            /** Zone Type */
            zone_type?: string | null;
        };
        /** TrafficCounterOut */
        TrafficCounterOut: {
            /** Counter Id */
            counter_id: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Name */
            name: string;
        };
        /** TransitionIn */
        TransitionIn: {
            /**
             * Actor
             * @description Who is making the change.
             * @default operator
             */
            actor: string;
            /** Note */
            note?: string | null;
            /**
             * To
             * @description Target status: acknowledged | dispatched | resolved.
             */
            to: string;
        };
        /**
         * TrustScoreOut
         * @description A trust score, inseparable from its explanation.
         *
         *     ``components`` and ``reason_codes`` are required and validated non-empty: a
         *     ``TrustScoreOut`` cannot be constructed as a bare number.
         */
        TrustScoreOut: {
            /** Components */
            components: components["schemas"]["ComponentOut"][];
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            };
            /** Notes */
            notes?: string[];
            /** Reason Codes */
            reason_codes: string[];
            risk: components["schemas"]["RiskOut"];
            /** Station Id */
            station_id: string;
            /** Timestamp Utc */
            timestamp_utc: string;
            /** Trust */
            trust: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VersionOut */
        VersionOut: {
            /** Config Hash */
            config_hash: string;
            /** Git Sha */
            git_sha: string;
            /** Model Versions */
            model_versions: {
                [key: string]: string;
            };
            /** Trust Config Hash */
            trust_config_hash: string;
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyOut"];
                };
            };
        };
    };
    model_drift_v1_admin_model_drift_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    retrain_v1_admin_retrain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrainIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_status_v1_admin_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_alerts_v1_alerts_get: {
        parameters: {
            query?: {
                /** @description Audit run; defaults to the latest. */
                run_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_v1_audit_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AuditRunOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_v1_audit_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dispatch_alert_v1_decision_dispatch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DispatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_signoff_v1_decision_signoff_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignoffIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_defects_v1_defects_get: {
        parameters: {
            query?: {
                code?: string | null;
                station?: string | null;
                severity?: string | null;
                start?: string | null;
                end?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DefectOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deweather_v1_deweather__station_id__get: {
        parameters: {
            query: {
                /** @description The pollutant to show the deweathered series for. */
                parameter: string;
            };
            header?: never;
            path: {
                station_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeweatherSeriesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_v1_events_get: {
        parameters: {
            query?: {
                station?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_EventOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_explain_v1_explain__defect_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                defect_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_trail_v1_export_audit_trail_get: {
        parameters: {
            query?: {
                /** @description Audit run; defaults to the latest. */
                run_id?: string | null;
                format?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_attention_overlay_v1_graph_attention_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttentionOverlayOut"];
                };
            };
        };
    };
    list_maintenance_v1_maintenance_get: {
        parameters: {
            query?: {
                /** @description Filter by lifecycle status. */
                status?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_dict_str__Any__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rebuild_v1_maintenance_rebuild_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RebuildIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_v1_maintenance__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_v1_maintenance__item_id__transition_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quality_summary_v1_quality_summary_get: {
        parameters: {
            query?: {
                /** @description Audit run; defaults to the latest. */
                run_id?: string | null;
                /** @description Uptime/calibration window start. */
                start?: string | null;
                /** @description Uptime/calibration window end. */
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualitySummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_readings_v1_readings_get: {
        parameters: {
            query?: {
                station?: string | null;
                parameter?: string | null;
                start?: string | null;
                end?: string | null;
                /** @description Annotate with audit reason codes. */
                quality_flagged?: boolean;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ReadingOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bus_stops_v1_reference_bus_stops_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceStopsOut"];
                };
            };
        };
    };
    traffic_counters_v1_reference_traffic_counters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceCountersOut"];
                };
            };
        };
    };
    list_stations_v1_stations_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_StationOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_station_v1_stations__station_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                station_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trust_v1_trust__station_id__get: {
        parameters: {
            query?: {
                /** @description Return the score history instead of the latest. */
                series?: boolean;
                start?: string | null;
                end?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                station_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrustScoreOut"] | components["schemas"]["Page_TrustScoreOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionOut"];
                };
            };
        };
    };
}
