// Generated by scripts/gen_frontend_contract.py. Do not edit by hand.
//
// Parsed from design/tokens/tokens.css. Only values the UI *branches* on live
// here - never colour, which stays in CSS behind var(). The trust thresholds
// are in the token file so the marker colour and the classification cannot
// disagree; this file keeps TypeScript reading the same single source.

/** Trust at or above this is verified. */
export const TRUST_VERIFIED_AT = 0.85;

/** Trust below this is a fault. Between the two is anomaly/ambiguity. */
export const TRUST_FAULT_BELOW = 0.5;

/** Shape channel, so colour is never the only signal a state carries. */
export const STATE_SHAPES = {
  verified: "circle-filled",
  degraded: "circle-half",
  fault: "circle-barred",
  ambiguous: "ring-dashed",
  noCoverage: "hatch",
} as const;
